import React, { useState } from 'react';
import { collection, doc, setDoc, writeBatch } from 'firebase/firestore';
import { db } from '../../services/firebaseService';
import { Dish } from '../../types';

export const DataSeeder: React.FC = () => {
    const [loading, setLoading] = useState(false);
    const [stats, setStats] = useState({ total: 0, success: 0, errors: 0 });
    const [log, setLog] = useState<string[]>([]);

    const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = async (e) => {
            try {
                const json = JSON.parse(e.target?.result as string);
                if (Array.isArray(json)) {
                    await seedDatabase(json);
                } else {
                    alert("Invalid JSON: Expected an array of dishes.");
                }
            } catch (error) {
                console.error("Parse Error", error);
                alert("Failed to parse JSON file.");
            }
        };
        reader.readAsText(file);
    };

    const seedDatabase = async (dishes: Dish[]) => {
        setLoading(true);
        setLog([]);
        setStats({ total: dishes.length, success: 0, errors: 0 });

        const batchSize = 100; // Firestore batch limit is 500
        let currentBatch = writeBatch(db);
        let count = 0;
        let successCount = 0;
        let errorCount = 0;

        for (const dish of dishes) {
            try {
                if (!dish.name) continue;

                // Ensure ID
                const id = dish.id || crypto.randomUUID();
                const docRef = doc(db, 'cached_dishes', id);

                // Add to batch
                currentBatch.set(docRef, { ...dish, id, isViral: true, ingestedAt: new Date().toISOString() });

                count++;

                // Commit if batch full
                if (count % batchSize === 0) {
                    await currentBatch.commit();
                    currentBatch = writeBatch(db);
                    successCount += batchSize;
                    setStats(s => ({ ...s, success: successCount }));
                    setLog(prev => [...prev.slice(-4), `Committed batch of ${batchSize}...`]);
                }
            } catch (e) {
                console.error("Skipping dish", dish.name, e);
                errorCount++;
            }
        }

        // Final commit
        if (count % batchSize !== 0) {
            await currentBatch.commit();
            successCount += (count % batchSize);
        }

        setStats({ total: dishes.length, success: successCount, errors: errorCount });
        setLoading(false);
        setLog(prev => [...prev, "Seeding Complete!"]);
    };

    return (
        <div className="p-6 bg-gray-900 text-white rounded-lg shadow-xl max-w-2xl mx-auto my-10 border border-gray-700">
            <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-500 mb-4">
                Viral Recipe Seeder
            </h2>
            <p className="text-gray-400 mb-6">
                Upload the <code>master_recipe_db.json</code> file generated by the ingestion script to populate the Firestore database.
            </p>

            <div className="mb-6">
                <input
                    type="file"
                    accept=".json"
                    onChange={handleFileUpload}
                    disabled={loading}
                    className="block w-full text-sm text-gray-400
                        file:mr-4 file:py-2 file:px-4
                        file:rounded-full file:border-0
                        file:text-sm file:font-semibold
                        file:bg-blue-600 file:text-white
                        hover:file:bg-blue-700
                        cursor-pointer"
                />
            </div>

            {loading && (
                <div className="mb-4">
                    <div className="w-full bg-gray-700 rounded-full h-2.5">
                        <div
                            className="bg-blue-600 h-2.5 rounded-full transition-all duration-300"
                            style={{ width: `${(stats.success / stats.total) * 100}%` }}
                        ></div>
                    </div>
                </div>
            )}

            <div className="grid grid-cols-3 gap-4 mb-6 text-center">
                <div className="p-3 bg-gray-800 rounded-lg">
                    <div className="text-sm text-gray-500">Total Recipes</div>
                    <div className="text-xl font-bold">{stats.total}</div>
                </div>
                <div className="p-3 bg-gray-800 rounded-lg border border-green-900/30">
                    <div className="text-sm text-green-500">Success</div>
                    <div className="text-xl font-bold text-green-400">{stats.success}</div>
                </div>
                <div className="p-3 bg-gray-800 rounded-lg border border-red-900/30">
                    <div className="text-sm text-red-500">Errors</div>
                    <div className="text-xl font-bold text-red-400">{stats.errors}</div>
                </div>
            </div>

            <div className="font-mono text-xs text-gray-500 bg-black/50 p-4 rounded h-32 overflow-y-auto">
                {log.map((l, i) => <div key={i}>{l}</div>)}
                {log.length === 0 && <span className="opacity-50">Waiting for upload...</span>}
            </div>
        </div>
    );
};
